<a href="https://colab.research.google.com/github/gongyujin/pydata/blob/master/11.deep/d0714/02%EB%94%A5%EB%9F%AC%EB%8B%9D_mnist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## keras 딥러닝 - mnist

In [75]:
from tensorflow import keras
import sklearn
from sklearn.linear_model import SGDClassifier # 확률적경사하강법
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [76]:
# 데이터불러오기
(train_data,train_label),(test_data,test_label)=keras.datasets.fashion_mnist.load_data()

In [77]:
# 데이터 전처리
# 1. 데이터 확인 - pandas : info, describe
print(train_data.shape) # (60000, 28, 28)
train_label.shape # (60000,)

(60000, 28, 28)


(60000,)

In [78]:
# 2. class 확인 - pandas : columns로 확인
np.unique(train_label,return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8),
 array([6000, 6000, 6000, 6000, 6000, 6000, 6000, 6000, 6000, 6000]))

In [79]:
# 3. 정규화, 표준화 작업
train_scaled=train_data/255.0
test_scaled=test_data/255.0

In [80]:
# train_scaled=train_scaled.reshape(-1,28*28)
# test_scaled=test_scaled.reshape(-1,28*28)

In [81]:
# train_data,test_data,val_data
sub_data,val_data,sub_label,val_label=train_test_split(train_scaled,train_label)

In [82]:
# 클래스 개수-10
np.unique(train_label)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [83]:
# ## 1. 딥러닝 선언
# # keras 기본층 - 제일마지막 dense층은 class 개수와 같아야함, class가 여러개이므로 activation='softmax'를 사용해야함
# # 클래스가 여러개, softmax사용 1개일때는 sigmoid 함수
# # 출력층
# dense = keras.layers.Dense(100,activation='sigmoid', input_shape=(784,))
# dense2 = keras.layers.Dense(10,activation='softmax')

# # 알고리즘선언
# model=keras.Sequential([dense,dense2])

# # 설정 - 이진분류 : sparse_binary_crossentropy, 다중분류 : sparse_categorical_crossentropy
# # accuracy : 정확도 출력
# model.compile(loss='sparse_categorical_crossentropy',metrics="accuracy")

In [84]:
# ## 2. 딥러닝 선언
# # keras 기본층 - 제일마지막 dense층은 class 개수와 같아야함, class가 여러개이므로 activation='softmax'를 사용해야함
# # 클래스가 여러개, softmax사용 1개일때는 sigmoid 함수
# # 출력층
# dense = keras.layers.Dense(100,activation='sigmoid', input_shape=(784,))
# dense2 = keras.layers.Dense(10,activation='softmax')

# # 알고리즘선언
# model=keras.Sequential([
#   keras.layers.Dense(100,activation='sigmoid', input_shape=(784,)),
#   keras.layers.Dense(10,activation='softmax')
# ])

# # 설정 - 이진분류 : sparse_binary_crossentropy, 다중분류 : sparse_categorical_crossentropy
# # accuracy : 정확도 출력
# model.compile(loss='sparse_categorical_crossentropy',metrics="accuracy")

In [85]:
## 3. 딥러닝 선언
# 알고리즘 선언
model=keras.Sequential()
model.add(keras.layers.Flatten(input_shape=(28,28))) 
model.add(keras.layers.Dense(100,activation="relu"))
model.add(keras.layers.Dense(10,activation="softmax",name='mnist'))
model.compile(loss='sparse_categorical_crossentropy',metrics="accuracy")

In [86]:
# 훈련 - 2차원데이터
model.fit(train_scaled,train_label,epochs=5)
# model.fit(sub_data,sub_label,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.5111 - accuracy: 0.8198
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3832 - accuracy: 0.8635
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3501 - accuracy: 0.8757
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3309 - accuracy: 0.8817
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3187 - accuracy: 0.8867


In [87]:
# 정확도
score=model.evaluate(test_scaled,test_label)
score

313/313 [==============================] - 1s 2ms/step - loss: 0.3848 - accuracy: 0.8725


[0.38481131196022034, 0.8725000023841858]

In [88]:
model.summary()

Model: "sequential_13"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_5 (Flatten)         (None, 784)               0         
                                                                 
 dense_28 (Dense)            (None, 100)               78500     
                                                                 
 mnist (Dense)               (None, 10)                1010      
                                                                 
Total params: 79,510
Trainable params: 79,510
Non-trainable params: 0
_________________________________________________________________
